spring.datasource.url=jdbc:postgresql://localhost:5432/geofenced_asset
spring.datasource.username=postgres
spring.datasource.password=Nooneleftbehind1@

#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#key=value only! No space in between